apiVersion: apps/v1
kind: Deployment
metadata:
  name: ade-postgresql-metrics
  labels:
    app: ade-postgresql-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ade-postgresql-metrics
  template:
    metadata:
      labels:
        app: ade-postgresql-metrics
    spec:
      containers:
        - name: postgresql
          image: image-registry.openshift-image-registry.svc:5000/dd-d2s-ade/ade-postgresql-metrics:latest
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: my-postgresql-credentials
                  key: POSTGRESQL_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-postgresql-credentials
                  key: POSTGQL_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: my-postgresql-credentials
                  key: POSTGQL_DATABASE
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-metrics-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ade-postgresql-metrics
  labels:
    app: ade-postgresql-metrics
spec:
  ports:
    - name: 5432-tcp
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: ade-postgresql-metrics
